// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Tnh2VruLU1TqUk0P519vJY_4RqI8-dE',
    appId: '1:95773927624:web:0c23816939901016081dfd',
    messagingSenderId: '95773927624',
    projectId: 'notes-21d69',
    authDomain: 'notes-21d69.firebaseapp.com',
    storageBucket: 'notes-21d69.firebasestorage.app',
    measurementId: 'G-8PRE4GV3L6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb8NbAVU6L1YxuI0r4PMFPkoRXwk2F1Vc',
    appId: '1:95773927624:android:5e2501a7384f7cc0081dfd',
    messagingSenderId: '95773927624',
    projectId: 'notes-21d69',
    storageBucket: 'notes-21d69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC996I4EeAg-OY6_rNONkpOV5epfxWKvdc',
    appId: '1:95773927624:ios:2239f763120adb70081dfd',
    messagingSenderId: '95773927624',
    projectId: 'notes-21d69',
    storageBucket: 'notes-21d69.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudBasio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC996I4EeAg-OY6_rNONkpOV5epfxWKvdc',
    appId: '1:95773927624:ios:2239f763120adb70081dfd',
    messagingSenderId: '95773927624',
    projectId: 'notes-21d69',
    storageBucket: 'notes-21d69.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudBasio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Tnh2VruLU1TqUk0P519vJY_4RqI8-dE',
    appId: '1:95773927624:web:c943e80d78afc009081dfd',
    messagingSenderId: '95773927624',
    projectId: 'notes-21d69',
    authDomain: 'notes-21d69.firebaseapp.com',
    storageBucket: 'notes-21d69.firebasestorage.app',
    measurementId: 'G-2HK42D1NT5',
  );
}
